# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  Bitsy_config = debug_x64
  rlights_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  Bitsy_config = debug_x86
  rlights_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  Bitsy_config = debug_arm64
  rlights_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  Bitsy_config = release_x64
  rlights_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  Bitsy_config = release_x86
  rlights_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  Bitsy_config = release_arm64
  rlights_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib Bitsy rlights

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C lib/raylib-master -f Makefile config=$(raylib_config)
endif

Bitsy: raylib rlights
ifneq (,$(Bitsy_config))
	@echo "==== Building Bitsy ($(Bitsy_config)) ===="
	@${MAKE} --no-print-directory -C bin/Debug/int -f Bitsy.make config=$(Bitsy_config)
endif

rlights:
ifneq (,$(rlights_config))
	@echo "==== Building rlights ($(rlights_config)) ===="
	@${MAKE} --no-print-directory -C bin/Debug/int -f rlights.make config=$(rlights_config)
endif

clean:
	@${MAKE} --no-print-directory -C lib/raylib-master -f Makefile clean
	@${MAKE} --no-print-directory -C bin/Debug/int -f Bitsy.make clean
	@${MAKE} --no-print-directory -C bin/Debug/int -f rlights.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   Bitsy"
	@echo "   rlights"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"